version: '3'
services:
  ocr-extraction:
    container_name: ocr-extraction
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
  format-files:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./helpers/docker_auto_format.sh
